### ISSUE TITLE
Add Login Screen

### ISSUE THREAD

**Issue by ExitTrance** [ExitTrance/KanjiMaru#4]

**Comment by keertirajmalik** [comment]
Still, working on this app? @ExitTrance

**Comment by ExitTrance** [comment]
@keertirajmalik Yep, still working on it. Currently just busy with other matters.

**Comment by keertirajmalik** [comment]
Do you have design for login page? I would like to work on it 😊 if you don't mind

**Comment by ExitTrance** [comment]
> @ExitTrance you have design for login page? I would like to work on it 😊 if you don't mind
Sorry, I do not have any designs of the login screen at the moment, since it's very low priority for me. I appreciate that you would like to work on it, but I believe I need to flesh it out this project a bit more. I can not possibly ask anyone to help me on this project, before I have a clear vision of this project myself. (Also, the structure is, to say the least, a bit embarrassing at the moment. Maybe not a great idea to make this repository public haha.) 😄

**Comment by keertirajmalik** [comment]
As you wish but do let me know if you need any help. As a beginner, I would like to work with someone so I can get more feedback on the work that will be beneficial for me. Also, don't think much about the structure at the moment that can be achieved over time 😎

**Comment by ExitTrance** [comment]
I hope this doesn't notify anyone. As the new release has a bunch of new additions, I think the login page would be a nice place to explore the adaptive capabilities of flutter, and try to cater to multiple platforms, without breaking any of the existing codebase.  Moving this to priority.

**Comment by keertirajmalik** [comment]
It notified me 😂

**Comment by ExitTrance** [comment]
Haha, sorry about that. Thought it would only notify on a mention. Tend to use github issues as a sort of mind board of sorts... D:
